import './global.css';

import Link from 'next/link';

export const metadata = {
  title: 'Welcome to blog',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-800 p-4 text-white">
          <nav className="container mx-auto p-4">
            <ul className="flex gap-4">
              <li>
                <Link href="/">Posts</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="container mx-auto flex flex-col gap-4 p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
